# Descriptor Computation Cronjob to compute missing descriptors for components
# Runs every 5 minutes
MAILTO="eschenbach@dg.tu-darmstadt.de"
*/5 * * * * source /home/ddu/.bash_profile && flock -n /tmp/descriptors_simple.lock /home/ddu/csc/venv/bin/python3.9 /home/ddu/csc/backend/main_descriptors_simple.py >> /home/ddu/csc/backend/logs/descriptors_simple_cronjob.log 2>&1