# Geometry Maintenance Cronjob to clean up obsolete geometry files
# Runs every day at 3:00 AM
MAILTO="eschenbach@dg.tu-darmstadt.de"
0 3 * * * source /home/ddu/.bash_profile && /home/ddu/csc/venv/bin/python3.9 /home/ddu/csc/backend/geometrymaintenance.py >> /home/ddu/csc/backend/logs/geometrymaintenance_cronjob.log 2>&1