# Geometry Maintenance Cronjob to clean up obsolete geometry files
# Runs every day at 3:00 AM
MAILTO="max.eschenbach@tu-darmstadt.de"
0 3 * * * source /home/ddu/.bash_profile && /home/ddu/csc/current/venv/bin/python /home/ddu/csc/current/backend/geometrymaintenance.py >> /home/ddu/csc/shared/logs/geometrymaintenance_cronjob.log 2>&1