# Preview Generation Cronjob to generate previews for components
# Runs every 30 minutes
MAILTO="eschenbach@dg.tu-darmstadt.de"
*/30 * * * * /home/ddu/csc/venv/bin/python3.9 /home/ddu/csc/backend/main_previewgen.py >> /home/ddu/csc/backend/logs/previewgen_cronjob.log 2>&1