# User Maintenance Cronjob to clean up unverified user accounts
# Runs every day at 2:00 AM
MAILTO="eschenbach@dg.tu-darmstadt.de"
0 2 * * * source /home/ddu/.bash_profile && /home/ddu/csc/venv/bin/python3.9 /home/ddu/csc/backend/usermaintenance.py >> /home/ddu/csc/backend/logs/usermaintenance_cronjob.log 2>&1