[program:fastapi]
directory=%(ENV_HOME)s/csc/backend
command=%(ENV_HOME)s/csc/venv/bin/gunicorn --config %(ENV_HOME)s/csc/backend/conf.py --reload
autostart=true
autorestart=true
# `startsecs` is set by Uberspace monitoring team, to prevent a broken service from looping
startsecs=30