[program:react-frontend]
directory=%(ENV_HOME)s/csc/frontend
command=npm run start
autostart=true
autorestart=true
environment=NODE_ENV=production
# `startsecs` is set by Uberspace monitoring team, to prevent a broken service from looping
startsecs=30
